// Generated by @dartnative/codegen:
// https://www.npmjs.com/package/@dartnative/codegen

import 'dart:ffi';

import 'package:dart_native/dart_native.dart';
import 'package:dart_native_gen/dart_native_gen.dart';

import 'unused/avmediaselectiongroup.dart';
// You can uncomment this line when this package is ready.
// import 'package:avfoundation/avbase.dart';
// You can uncomment this line when this package is ready.
// import 'package:foundation/foundation.dart';

@native

///
class AVAssetCache extends NSObject {
  ///
  AVAssetCache([Class isa]) : super(isa ?? Class('AVAssetCache'));

  ///
  AVAssetCache.fromPointer(Pointer<Void> ptr) : super.fromPointer(ptr);

  ///
  bool get playableOffline {
    return perform(SEL('playableOffline')) as bool;
  }

  ///
  set playableOffline(bool playableOffline) =>
      perform(SEL('setPlayableOffline:'), args: <bool>[playableOffline]);

  AVMediaSelectionOption mediaSelectionOptionsInMediaSelectionGroup(
      AVMediaSelectionGroup mediaSelectionGroup) {
    Pointer<Void> result = perform(
        SEL('mediaSelectionOptionsInMediaSelectionGroup:'),
        args: <AVMediaSelectionGroup>[mediaSelectionGroup],
        decodeRetVal: false) as Pointer<Void>;
    return AVMediaSelectionOption.fromPointer(result);
  }
}
// You can uncomment this line when this package is ready.
// import 'package:avfcore/avassetcache.dart';
