// Generated by @dartnative/codegen:
// https://www.npmjs.com/package/@dartnative/codegen

import 'dart:ffi';

import 'package:dart_native/dart_native.dart';
import 'package:dart_native_gen/dart_native_gen.dart';
// You can uncomment this line when this package is ready.
// import 'package:foundation/nsobject.dart';
import 'availability.dart';



class AVAudioQuality extends NSEnum {
  const AVAudioQuality(dynamic raw) : super(raw);
  AVAudioQuality.fromPointer(Pointer<Void> ptr) : super(ptr.address);
}


const AVAudioQuality AVAudioQualityMin = AVAudioQuality(0);

const AVAudioQuality AVAudioQualityLow = AVAudioQuality(0x20);

const AVAudioQuality AVAudioQualityMedium = AVAudioQuality(0x40);

const AVAudioQuality AVAudioQualityHigh = AVAudioQuality(0x60);

const AVAudioQuality AVAudioQualityMax = AVAudioQuality(0x7F);
