// Generated by @dartnative/codegen:
// https://www.npmjs.com/package/@dartnative/codegen

import 'dart:ffi';

import 'package:dart_native/dart_native.dart';
import 'package:dart_native_gen/dart_native_gen.dart';
// You can uncomment this line when this package is ready.
// import 'package:avfoundation/avbase.dart';
// You can uncomment this line when this package is ready.
// import 'package:foundation/foundation.dart';

@NativeAvailable(macos: '10.7', ios: '4.0', tvos: '9.0', watchos: '1.0') @NativeAvailable(macos: '10.10') @NativeUnavailable(ios, tvos, watchos)
@native
class AVPlayerItemTrack extends NSObject {
  AVPlayerItemTrack([Class isa]) : super(isa ?? Class('AVPlayerItemTrack'));
  AVPlayerItemTrack.fromPointer(Pointer<Void> ptr) : super.fromPointer(ptr);
  
  AVAssetTrack get assetTrack {
Pointer<Void> result = perform(SEL('assetTrack'), decodeRetVal: false);
    return AVAssetTrack.fromPointer(result);

}
  
  set assetTrack(AVAssetTrack assetTrack) => perform(SEL('setAssetTrack:'), args: [assetTrack]);
  
  bool get enabled {
return perform(SEL('enabled'));

}
  
  set enabled(bool enabled) => perform(SEL('setEnabled:'), args: [enabled]);
  @NativeAvailable(macos: '10.9', ios: '7.0', tvos: '9.0') @NativeUnavailable(watchos)
  double get currentVideoFrameRate {
return perform(SEL('currentVideoFrameRate'));

}
  @NativeAvailable(macos: '10.9', ios: '7.0', tvos: '9.0') @NativeUnavailable(watchos)
  set currentVideoFrameRate(double currentVideoFrameRate) => perform(SEL('setCurrentVideoFrameRate:'), args: [currentVideoFrameRate]);
  @NativeAvailable(macos: '10.10') @NativeUnavailable(ios, tvos, watchos)
  String get videoFieldMode {
Pointer<Void> result = perform(SEL('videoFieldMode'), decodeRetVal: false);
    return NSString.fromPointer(result).raw;

}
  @NativeAvailable(macos: '10.10') @NativeUnavailable(ios, tvos, watchos)
  set videoFieldMode(String videoFieldMode) => perform(SEL('setVideoFieldMode:'), args: [videoFieldMode]);

}
// You can uncomment this line when this package is ready.
// import 'package:avfcore/avplayeritemtrack.dart';